### ISSUE TITLE
panic on no connection

### ISSUE THREAD

**Issue by pmalek** [pmalek/kernel_deb_downloader#1]
```
kernel_deb_downloader -n
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x475848]

goroutine 1 [running]:
panic(0x7649e0, 0xc820010170)
        /home/patryk/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
github.com/pmalek/kernel_deb_downloader/ubuntukernelpageutils.parseKernelPage(0x0)
        /home/patryk/.gvm/pkgsets/go1.6.2/global/src/github.com/pmalek/kernel_deb_downloader/ubuntukernelpageutils/ubuntukernelpageutils.go:21 +0x488
github.com/pmalek/kernel_deb_downloader/ubuntukernelpageutils.GetMostActualKernelVersion(0x0, 0x0, 0x0, 0x0)
        /home/patryk/.gvm/pkgsets/go1.6.2/global/src/github.com/pmalek/kernel_deb_downloader/ubuntukernelpageutils/ubuntukernelpageutils.go:95 +0x34
main.main()
        /home/patryk/.gvm/pkgsets/go1.6.2/global/src/github.com/pmalek/kernel_deb_downloader/kernel_deb_downloader.go:20 +0x293
```

**Comment by pmalek** [comment]
Resolved
